/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package tech.dev.eVoyageBackend.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// API_LOGS
	VIEW_API_LOGS("VIEW_API_LOGS"),	
	CREATE_API_LOGS("CREATE_API_LOGS"),
	UPDATE_API_LOGS("UPDATE_API_LOGS"),
	DELETE_API_LOGS("DELETE_API_LOGS"),
	// API_USER
	VIEW_API_USER("VIEW_API_USER"),	
	CREATE_API_USER("CREATE_API_USER"),
	UPDATE_API_USER("UPDATE_API_USER"),
	DELETE_API_USER("DELETE_API_USER"),
	// CARDS
	VIEW_CARDS("VIEW_CARDS"),	
	CREATE_CARDS("CREATE_CARDS"),
	UPDATE_CARDS("UPDATE_CARDS"),
	DELETE_CARDS("DELETE_CARDS"),
	// CUSTOMERS
	VIEW_CUSTOMERS("VIEW_CUSTOMERS"),	
	CREATE_CUSTOMERS("CREATE_CUSTOMERS"),
	UPDATE_CUSTOMERS("UPDATE_CUSTOMERS"),
	DELETE_CUSTOMERS("DELETE_CUSTOMERS"),
	// FONCTIONALITE
	VIEW_FONCTIONALITE("VIEW_FONCTIONALITE"),	
	CREATE_FONCTIONALITE("CREATE_FONCTIONALITE"),
	UPDATE_FONCTIONALITE("UPDATE_FONCTIONALITE"),
	DELETE_FONCTIONALITE("DELETE_FONCTIONALITE"),
	// LOGS
	VIEW_LOGS("VIEW_LOGS"),	
	CREATE_LOGS("CREATE_LOGS"),
	UPDATE_LOGS("UPDATE_LOGS"),
	DELETE_LOGS("DELETE_LOGS"),
	// PARAM_NOTIFICATION
	VIEW_PARAM_NOTIFICATION("VIEW_PARAM_NOTIFICATION"),	
	CREATE_PARAM_NOTIFICATION("CREATE_PARAM_NOTIFICATION"),
	UPDATE_PARAM_NOTIFICATION("UPDATE_PARAM_NOTIFICATION"),
	DELETE_PARAM_NOTIFICATION("DELETE_PARAM_NOTIFICATION"),
	// PARAMETRE_GENERAUX
	VIEW_PARAMETRE_GENERAUX("VIEW_PARAMETRE_GENERAUX"),	
	CREATE_PARAMETRE_GENERAUX("CREATE_PARAMETRE_GENERAUX"),
	UPDATE_PARAMETRE_GENERAUX("UPDATE_PARAMETRE_GENERAUX"),
	DELETE_PARAMETRE_GENERAUX("DELETE_PARAMETRE_GENERAUX"),
	// ROLE
	VIEW_ROLE("VIEW_ROLE"),	
	CREATE_ROLE("CREATE_ROLE"),
	UPDATE_ROLE("UPDATE_ROLE"),
	DELETE_ROLE("DELETE_ROLE"),
	// ROLE_FONCTIONALITE
	VIEW_ROLE_FONCTIONALITE("VIEW_ROLE_FONCTIONALITE"),	
	CREATE_ROLE_FONCTIONALITE("CREATE_ROLE_FONCTIONALITE"),
	UPDATE_ROLE_FONCTIONALITE("UPDATE_ROLE_FONCTIONALITE"),
	DELETE_ROLE_FONCTIONALITE("DELETE_ROLE_FONCTIONALITE"),
	// TRANSACTIONS
	VIEW_TRANSACTIONS("VIEW_TRANSACTIONS"),	
	CREATE_TRANSACTIONS("CREATE_TRANSACTIONS"),
	UPDATE_TRANSACTIONS("UPDATE_TRANSACTIONS"),
	DELETE_TRANSACTIONS("DELETE_TRANSACTIONS"),
	// USER
	VIEW_USER("VIEW_USER"),	
	CREATE_USER("CREATE_USER"),
	UPDATE_USER("UPDATE_USER"),
	DELETE_USER("DELETE_USER"),
	// ALERTS
	VIEW_ALERTS("VIEW_ALERTS"),
	CREATE_ALERTS("CREATE_ALERTS"),
	UPDATE_ALERTS("UPDATE_ALERTS"),
	DELETE_ALERTS("DELETE_ALERTS"),
	// CITIES
	VIEW_CITIES("VIEW_CITIES"),
	CREATE_CITIES("CREATE_CITIES"),
	UPDATE_CITIES("UPDATE_CITIES"),
	DELETE_CITIES("DELETE_CITIES"),
	// BOOKINGS
	VIEW_BOOKINGS("VIEW_BOOKINGS"),
	CREATE_BOOKINGS("CREATE_BOOKINGS"),
	UPDATE_BOOKINGS("UPDATE_BOOKINGS"),
	DELETE_BOOKINGS("DELETE_BOOKINGS"),
	// BUSES
	VIEW_BUSES("VIEW_BUSES"),
	CREATE_BUSES("CREATE_BUSES"),
	UPDATE_BUSES("UPDATE_BUSES"),
	DELETE_BUSES("DELETE_BUSES"),
	// COMPANIES
	VIEW_COMPANIES("VIEW_COMPANIES"),
	CREATE_COMPANIES("CREATE_COMPANIES"),
	UPDATE_COMPANIES("UPDATE_COMPANIES"),
	DELETE_COMPANIES("DELETE_COMPANIES"),
	// FINANCIAL_REPORTS
	VIEW_FINANCIAL_REPORTS("VIEW_FINANCIAL_REPORTS"),
	CREATE_FINANCIAL_REPORTS("CREATE_FINANCIAL_REPORTS"),
	UPDATE_FINANCIAL_REPORTS("UPDATE_FINANCIAL_REPORTS"),
	DELETE_FINANCIAL_REPORTS("DELETE_FINANCIAL_REPORTS"),
	// NOTIFICATIONS
	VIEW_NOTIFICATIONS("VIEW_NOTIFICATIONS"),
	CREATE_NOTIFICATIONS("CREATE_NOTIFICATIONS"),
	UPDATE_NOTIFICATIONS("UPDATE_NOTIFICATIONS"),
	DELETE_NOTIFICATIONS("DELETE_NOTIFICATIONS"),
	// PAYMENTS
	VIEW_PAYMENTS("VIEW_PAYMENTS"),
	CREATE_PAYMENTS("CREATE_PAYMENTS"),
	UPDATE_PAYMENTS("UPDATE_PAYMENTS"),
	DELETE_PAYMENTS("DELETE_PAYMENTS"),
	// ROLES
	VIEW_ROLES("VIEW_ROLES"),
	CREATE_ROLES("CREATE_ROLES"),
	UPDATE_ROLES("UPDATE_ROLES"),
	DELETE_ROLES("DELETE_ROLES"),
	// ROUTES
	VIEW_ROUTES("VIEW_ROUTES"),
	CREATE_ROUTES("CREATE_ROUTES"),
	UPDATE_ROUTES("UPDATE_ROUTES"),
	DELETE_ROUTES("DELETE_ROUTES"),
	// TICKETS
	VIEW_TICKETS("VIEW_TICKETS"),
	CREATE_TICKETS("CREATE_TICKETS"),
	UPDATE_TICKETS("UPDATE_TICKETS"),
	DELETE_TICKETS("DELETE_TICKETS"),
	// TRIP_TRACKING
	VIEW_TRIP_TRACKING("VIEW_TRIP_TRACKING"),
	CREATE_TRIP_TRACKING("CREATE_TRIP_TRACKING"),
	UPDATE_TRIP_TRACKING("UPDATE_TRIP_TRACKING"),
	DELETE_TRIP_TRACKING("DELETE_TRIP_TRACKING"),
	// USER_ROLES
	VIEW_USER_ROLES("VIEW_USER_ROLES"),
	CREATE_USER_ROLES("CREATE_USER_ROLES"),
	UPDATE_USER_ROLES("UPDATE_USER_ROLES"),
	DELETE_USER_ROLES("DELETE_USER_ROLES"),
	// USERS
	VIEW_USERS("VIEW_USERS"),
	CREATE_USERS("CREATE_USERS"),
	UPDATE_USERS("UPDATE_USERS"),
	DELETE_USERS("DELETE_USERS"),


	// PERMISSIONS
	VIEW_PERMISSIONS("VIEW_PERMISSIONS"),
	CREATE_PERMISSIONS("CREATE_PERMISSIONS"),
	UPDATE_PERMISSIONS("UPDATE_PERMISSIONS"),
	DELETE_PERMISSIONS("DELETE_PERMISSIONS"),
	// ROLE_PERMISSIONS
	VIEW_ROLE_PERMISSIONS("VIEW_ROLE_PERMISSIONS"),
	CREATE_ROLE_PERMISSIONS("CREATE_ROLE_PERMISSIONS"),
	UPDATE_ROLE_PERMISSIONS("UPDATE_ROLE_PERMISSIONS"),
	DELETE_ROLE_PERMISSIONS("DELETE_ROLE_PERMISSIONS"),
	// TRAVEL_SCHEDULES
	VIEW_TRAVEL_SCHEDULES("VIEW_TRAVEL_SCHEDULES"),
	CREATE_TRAVEL_SCHEDULES("CREATE_TRAVEL_SCHEDULES"),
	UPDATE_TRAVEL_SCHEDULES("UPDATE_TRAVEL_SCHEDULES"),
	DELETE_TRAVEL_SCHEDULES("DELETE_TRAVEL_SCHEDULES"),
	// DEPARTS
	VIEW_DEPARTS("VIEW_DEPARTS"),
	CREATE_DEPARTS("CREATE_DEPARTS"),
	UPDATE_DEPARTS("UPDATE_DEPARTS"),
	DELETE_DEPARTS("DELETE_DEPARTS"),
	// DISTRICTS
	VIEW_DISTRICTS("VIEW_DISTRICTS"),
	CREATE_DISTRICTS("CREATE_DISTRICTS"),
	UPDATE_DISTRICTS("UPDATE_DISTRICTS"),
	DELETE_DISTRICTS("DELETE_DISTRICTS"),
	// STATIONS
	VIEW_STATIONS("VIEW_STATIONS"),
	CREATE_STATIONS("CREATE_STATIONS"),
	UPDATE_STATIONS("UPDATE_STATIONS"),
	DELETE_STATIONS("DELETE_STATIONS");
	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
