/*
 * Created on 2024-11-25 ( Time 15:12:19 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package tech.dev.eVoyageBackend.dao.entity;

import lombok.Data;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * Persistent class for entity stored in table "api_logs"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="api_logs" )
public class ApiLogs implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="request_time", nullable=false)
    private Date       requestTime  ;

    @Column(name="request_url", length=255)
    private String     requestUrl   ;

    @Column(name="request_method", length=10)
    private String     requestMethod ;

    @Lob
    @Column(name="request_headers")
    private String     requestHeaders ;

    @Lob
    @Column(name="request_body")
    private String     requestBody  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="response_time", nullable=false)
    private Date       responseTime ;

    @Column(name="response_status")
    private Integer    responseStatus ;

    @Lob
    @Column(name="response_body")
    private String     responseBody ;

    @Column(name="created_by", length=255)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="last_modified_by", length=255)
    private String     lastModifiedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified_date", nullable=false)
    private Date       lastModifiedDate ;

    @Column(name="status", length=50)
    private String     status       ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ApiLogs() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
