/*
 * Created on 2025-01-21 ( Time 18:28:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package tech.dev.eVoyageBackend.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "departs"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="departs" )
public class Departs implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="departure_date", nullable=false)
    private Date       departureDate ;

    @Temporal(TemporalType.TIME)
    @Column(name="departure_time", nullable=false)
    private Date       departureTime ;

    @Column(name="duration")
    private Integer    duration     ;

    @Column(name="price", nullable=false)
    private Double     price        ;

    @Column(name="max_seats", nullable=false)
    private Integer    maxSeats     ;

    @Column(name="available_seats", nullable=false)
    private Integer    availableSeats ;

    @Column(name="is_active")
    private Boolean    isActive     ;

    @Column(name="rating")
    private Double     rating       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

	// "busId" (column "bus_id") is not defined by itself because used as FK in a link 
	// "originStationId" (column "origin_station_id") is not defined by itself because used as FK in a link 
	// "destinationStationId" (column "destination_station_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="bus_id", referencedColumnName="id")
    private Buses buses       ;
    @ManyToOne
    @JoinColumn(name="destination_station_id", referencedColumnName="id")
    private Stations stations2   ;
    @ManyToOne
    @JoinColumn(name="origin_station_id", referencedColumnName="id")
    private Stations stations    ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Departs() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
