/*
 * Created on 2024-08-20 ( Time 10:24:21 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package tech.dev.eVoyageBackend.dao.entity;

import lombok.Data;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * Persistent class for entity stored in table "logs"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="logs" )
public class Logs implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="action_service", length=255)
    private String     actionService ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date")
    private Date       date         ;

    @Column(name="id_status")
    private Integer    idStatus     ;

    @Column(name="ipadress", length=100)
    private String     ipadress     ;

    @Column(name="is_connexion")
    private Boolean    isConnexion  ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="login", length=60)
    private String     login        ;

    @Column(name="machine", length=255)
    private String     machine      ;

    @Column(name="nom", length=60)
    private String     nom          ;

    @Column(name="prenom", length=60)
    private String     prenom       ;

    @Column(name="request", length=2147483647)
    private String     request      ;

    @Column(name="response", length=2147483647)
    private String     response     ;

    @Column(name="search_string", length=10000)
    private String     searchString ;

    @Column(name="status_connection", length=100)
    private String     statusConnection ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="uri", length=255)
    private String     uri          ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Logs() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
