/*
 * Created on 2025-01-12 ( Time 17:39:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package tech.dev.eVoyageBackend.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "payments"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="payments" )
public class Payments implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="amount", nullable=false)
    private Double     amount       ;

    @Column(name="payment_method", nullable=false, length=50)
    private String     paymentMethod ;

    @Column(name="status", nullable=false, length=50)
    private String     status       ;

    @Column(name="reference", length=50)
    private String     reference       ;

    @Column(name="transaction_id", length=50)
    private String     transactionId       ;

    @Column(name="currency", length=3)
    private String     currency     ;

    @Column(name="numero_tel", length=50)
    private String     numeroTel    ;

    @Column(name="card_credit", length=50)
    private String     cardCredit   ;

    @Column(name="card_type", length=50)
    private String     cardType   ;

    @Column(name="card_holder",  length=50)
    private String     cardHolder   ;

    @Column(name="card_expiry",  length=50)
    private String     cardExpiry   ;

    @Column(name="card_cvv",  length=50)
    private String     cardCvv   ;

    @Column(name="card_issuer",length=50)
    private String     cardIssuer   ;

    @Column(name="card_country", length=50)
    private String     cardCountry   ;

    @Column(name="card_expire", length=50)
    private String     cardExpire   ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

	// "bookingId" (column "booking_id") is not defined by itself because used as FK in a link 
	// "companyId" (column "company_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="booking_id", referencedColumnName="id")
    private Bookings bookings    ;
    @ManyToOne
    @JoinColumn(name="company_id", referencedColumnName="id")
    private Companies companies   ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Payments() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
