/*
 * Created on 2025-01-12 ( Time 17:39:58 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package tech.dev.eVoyageBackend.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "travel_schedules"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="travel_schedules" )
public class TravelSchedules implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="departure_station", nullable=false, length=100)
    private String     departureStation ;

    @Column(name="arrival_station", nullable=false, length=100)
    private String     arrivalStation ;

    @Temporal(TemporalType.TIME)
    @Column(name="departure_time", nullable=false)
    private Date       departureTime ;

    @Temporal(TemporalType.TIME)
    @Column(name="arrival_time", nullable=false)
    private Date       arrivalTime  ;

    @Temporal(TemporalType.DATE)
    @Column(name="travel_date", nullable=false)
    private Date       travelDate   ;

    @Column(name="price", nullable=false)
    private Double     price        ;

    @Column(name="status", nullable=false, length=50)
    private String     status       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

	// "companyId" (column "company_id") is not defined by itself because used as FK in a link 
	// "routeId" (column "route_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="route_id", referencedColumnName="id")
    private Routes routes      ;
    @ManyToOne
    @JoinColumn(name="company_id", referencedColumnName="id")
    private Companies companies   ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TravelSchedules() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
